# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  imageName: 'ad-collector-webui:$(Build.BuildId)'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm test
    echo "List all files"
    ls -al
    echo "Building Docker Image"
    docker build -f ./src/webui/Dockerfile -t $(dockerId)/$(imageName) $(Build.SourcesDirectory)
    docker login -u $(dockerId) -p $(dockerPassword)
    "Pushing Image to Docker Hub"
    docker push $(dockerId)/$(imageName)
  displayName: 'Test and Push Docker Image'
