# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  imageName: 'ad-collector-webui'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm test
  displayName: 'Install and Test'

- script: |
    docker build -f ./src/webui/Dockerfile -t $(dockerId)/$(imageName):$(Build.BuildId) $(Build.SourcesDirectory)
    docker build -f ./src/webui/Dockerfile -t $(dockerId)/$(imageName):latest $(Build.SourcesDirectory)
    docker login -u $(dockerId) -p $(dockerPassword)
    docker push $(dockerId)/$(imageName):latest
    docker push $(dockerId)/$(imageName):$(Build.BuildId)
  displayName: 'Build and Push Docker Image'

- publish: $(System.DefaultWorkingDirectory)/docker
  artifact: AdCollectorDocker

- publish: $(System.DefaultWorkingDirectory)/caddy
  artifact: AdCollectorCaddy
