# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  imageName: 'ad-collector-webui'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm test
  displayName: 'npm install and test'

- task: Docker@2
  displayName: Build WebUI image
  inputs:
    repository: $(imageName)
    command: build
    Dockerfile: src/webui/Dockerfile

# - task: Docker@2
#   displayName: Push WebUI image
#   inputs:
#     containerRegistry: |
#       $(DockerHub)
#     repository: $(imageName)
#     command: push
#     tags: |
#       latest
