version: '3.7'
services:
  webui:
    build:
      context: .
      dockerfile: src/webui/Dockerfile
    entrypoint: ./node_modules/.bin/nodemon --mode development --exec 'babel-node index.js' 
    ports:
      - '4000:80'
    environment:
      - COOKIE_SECRET=some_password_string_with_32_characters
      - JWT_SECRET=some_password_string_with_32_characters
      - MONGO_URL=mongodb://mongo_user:mongo_pass@mongo_host:27017/mongo_database
    volumes:
      - './src/webui/plugins:/usr/src/app/plugins'
      - './src/webui/public:/usr/src/app/public'
      - './src/webui/lib:/usr/src/app/lib'
      - './src/webui/models:/usr/src/app/models'
      - './src/webui/services:/usr/src/app/services'
      - './src/webui/index.js:/usr/src/app/index.js'
      - './src/webui/server.js:/usr/src/app/server.js'
      - './src/webui/config.js:/usr/src/app/config.js'
      - './src/webui/constants.js:/usr/src/app/constants.js'
    networks:
      - colnet
networks:
  colnet:
