version: '3.7'
services:
  webui:
    build:
      context: .
      dockerfile: src/webui/Dockerfile
    entrypoint: ./node_modules/.bin/nodemon --mode development --exec 'babel-node index.js' 
    ports:
      - '4000:80'
    environment:
      - COOKIE_SECRET=some_password_string_with_32_characters
      - JWT_SECRET=some_password_string_with_32_characters
      - MONGO_URL=mongodb://admin:mongo_staging_fnetgh.com@ad-collector.apps.aduwillie.com:27017/adcollector
    volumes:
      - './src/webui/backend/plugins:/usr/src/app/plugins'
      - './src/webui/backend/public:/usr/src/app/public'
      - './src/webui/backend/lib:/usr/src/app/lib'
      - './src/webui/backend/models:/usr/src/app/models'
      - './src/webui/backend/services:/usr/src/app/services'
      - './src/webui/backend/index.js:/usr/src/app/index.js'
      - './src/webui/backend/server.js:/usr/src/app/server.js'
      - './src/webui/backend/config.js:/usr/src/app/config.js'
      - './src/webui/backend/constants.js:/usr/src/app/constants.js'
    networks:
      - colnet
networks:
  colnet:
