- name: "Uninstalling Docker Compose"
  shell: |
    rm /usr/local/bin/docker-compose

- name: "Uninstalling Docker"
  apt:
    name: "{{ packages }}"
    state: absent
    purge: yes
    update_cache: yes
  vars:
    packages:
      - docker
      - docker.io
