version: '3.7'
services:
  caddy:
    image: stefanprodan/caddy
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - '/projects/ad-collector/caddy:/etc/caddy/'
    networks:
      - colnet
  webui:
    image: aduwillie/ad-collector-webui:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - colnet
networks:
  colnet:
