version: '3.7'
services:
  webui:
    image: ad-collector-webui:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - "5000:80"
    networks:
      - colnet
networks:
  colnet:
