- name: "Join As A Swarm Worker"
  shell: |
    docker swarm join --token {{ hostvars[groups['swarm_manager'][0]]['manager_token']['stdout'] }} {{ hostvars[groups['swarm_manager'][0]]['ansible_eth0']['ipv4']['address'] }}:2377
  when: docker_info.stdout.find("Swarm{{':'}} inactive") != -1
  retries: 3
  delay: 20

