- name: "Installing Docker Dependencies"
  apt: 
    name: "{{ packages }}"
    state: latest
    update_cache: yes
  vars:
    packages:
      - ca-certificates
      - curl
      - software-properties-common
      - apt-transport-https

- name: "Installing Docker"
  apt:
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
      - docker
      - docker.io

- name: "Get Docker Info"
  shell: |
    docker info
  register: docker_info
  changed_when: false 
  
- name: "Installing Docker Compose"
  shell: |
    curl -L "https://github.com/docker/compose/releases/download/1.24.1/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
    sudo chmod +x /usr/local/bin/docker-compose
    sudo ln -s /usr/local/bin/docker-compose /usr/bin/docker-compose
    # add command completion
    curl -L https://raw.githubusercontent.com/docker/compose/1.24.1/contrib/completion/bash/docker-compose -o /etc/bash_completion.d/docker-compose
    docker-compose --version
  register: docker_compose_info

- name: "Remove Useless Packages From The Cache"
  apt:
    autoclean: yes

- name: "Remove Dependencies That Are No Longer Required"
  apt:
    autoremove: yes
